# this Dockerfile build an image that can be used as rootfs for Docker volume driver

# build container
FROM golang:1.11 as builder
WORKDIR /go/src/github.com/Nexenta/nexenta-docker-driver/
COPY .git ./.git
COPY cmd ./cmd
COPY pkg ./pkg
COPY vendor ./vendor
COPY Makefile ./Makefile
RUN make build-go

# driver rootfs container
FROM alpine:3.9.2
COPY --from=builder /go/src/github.com/Nexenta/nexenta-docker-driver/bin/nvd /bin/nvd
RUN /bin/nvd --version
RUN mkdir -p /mnt/nvd
ENTRYPOINT ["bin/sh"]
