# this Dockerfile build an image that can be used as rootfs for Docker volume plugin

# build container
FROM golang:1.12 as builder
WORKDIR /go/src/github.com/Nexenta/nexentastor-docker-volume-plugin/
COPY .git ./.git
COPY cmd ./cmd
COPY pkg ./pkg
COPY vendor ./vendor
COPY Makefile ./Makefile
ARG VERSION
ENV VERSION=$VERSION
RUN make build-go

# plugin rootfs container
FROM alpine:3.9.2
COPY --from=builder /go/src/github.com/Nexenta/nexentastor-docker-volume-plugin/bin/nexentastor-docker-volume-plugin /bin/nexentastor-docker-volume-plugin
RUN /bin/nexentastor-docker-volume-plugin --version
RUN mkdir -p /mnt/nexentastor-docker-volume-plugin
ENTRYPOINT ["bin/sh"]
