# pre-release container generates:
# - CNAHGELOG.md

FROM golang:1.11

WORKDIR /go/src/github.com/Nexenta/nexenta-docker-driver/

# deps
RUN go get github.com/git-chglog/git-chglog/cmd/git-chglog

# source code
COPY . ./

# next release tag
ARG VERSION
ENV VERSION=$VERSION

# generate changelkog
RUN echo "Use version: $VERSION" && /go/bin/git-chglog --next-tag ${VERSION} -o CHANGELOG.md

ENTRYPOINT ["/bin/bash"]
